name: Windows CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build Debug
      run: cargo build --all --verbose
    - name: Build Release
      run: cargo build --release --all --verbose

    - name: Run Debug Tests
      run: cargo test --all --verbose
    - name: Run Release Tests
      run: cargo test --release --all --verbose -- --include-ignored
